version: '3.1'

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always

    nimbus:
        image: storm
        container_name: nimbus
        command: storm nimbus
        depends_on:
            - zookeeper
        restart: always
        ports:
            - 6627:6627

    supervisor:
        image: storm
        command: storm supervisor
        depends_on:
            - nimbus
            - zookeeper
        restart: always

    ui:
        image: storm
        command: storm ui
        depends_on:
            - nimbus
        restart: always
        ports:
            - 8080:8080

    kafka:
        image: wurstmeister/kafka
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
        environment:
          HOSTNAME_COMMAND: "hostname -I | awk -F' ' '{print $$1}'"
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_CREATE_TOPICS: "test.command:1:1,test.warm.request:1:1,test.warm.response:1:1"
          KAFKA_ADVERTISED_PORT: 9092
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock